# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-03 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180819_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Фотографії'},
        ),
        migrations.AlterField(
            model_name='album',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(default='Portfolio', max_length=70, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToUUID(path='photos'), verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_cover_photo',
            field=models.BooleanField(verbose_name='Is cover photo '),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name'),
        ),
    ]
