# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-20 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('gallery', '0003_auto_20180420_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
