# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-23 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_album_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='company',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
            preserve_default=False,
        ),
    ]
