# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-02 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20180523_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(default='Portfolio', max_length=70, verbose_name='Имя'),
        ),
    ]
