# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='img_profile', verbose_name='Аватарка'),
        ),
    ]
