# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171106_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
