# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Имя тега')),
                ('slug', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Toaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='Имя')),
                ('address', models.CharField(max_length=140, verbose_name='Адрес')),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('site', models.CharField(max_length=50, verbose_name='Сайт')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(to='toast.Tag')),
            ],
        ),
    ]
