# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True),
        ),
    ]
