# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=140, verbose_name='Имя'),
        ),
    ]
