# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toast', '0002_auto_20171019_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toaster',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='toaster',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='upload/img', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
