# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast', '0002_auto_20171217_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
