# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast', '0003_auto_20171025_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toaster',
            name='img',
            field=models.ImageField(upload_to='img', verbose_name='Картинка'),
        ),
    ]
