# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 15:36
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('toast', '0004_auto_20171025_0801'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='toaster',
            managers=[
                ('pub_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
