# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toast', '0006_toaster_publish'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='toaster',
            managers=[
            ],
        ),
    ]
