# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast', '0007_auto_20171022_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToasterLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Город')),
                ('slug', models.SlugField(blank=True, max_length=140, null=True)),
            ],
        ),
    ]
