# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toast', '0008_toasterlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='toaster',
            name='locations',
            field=models.ManyToManyField(to='toast.ToasterLocation', verbose_name='Город'),
        ),
    ]
