# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-04 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20180220_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='publish',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Publish'),
        ),
    ]
