# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(db_index=True, default=True, verbose_name='Публикация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=140, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=140, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('site', models.CharField(blank=True, max_length=50, verbose_name='Site')),
                ('description', models.TextField(blank=True, max_length=350, verbose_name='Description')),
                ('img', models.ImageField(blank=True, upload_to='img', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(db_index=True, default=True, verbose_name='Публикация')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='City')),
                ('slug', models.SlugField(blank=True, max_length=140, null=True)),
            ],
            options={
                'verbose_name': 'Location',
                'ordering': ['name'],
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(db_index=True, default=True, verbose_name='Публикация')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Price')),
                ('slug', models.SlugField(blank=True, max_length=140, null=True)),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(db_index=True, default=True, verbose_name='Публикация')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Tag name')),
                ('slug', models.SlugField(blank=True, max_length=140, null=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='TypeCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(db_index=True, default=True, verbose_name='Публикация')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Company type')),
                ('slug', models.SlugField(blank=True, max_length=140, null=True)),
            ],
            options={
                'verbose_name': 'Company type',
                'ordering': ['name'],
                'verbose_name_plural': 'Company types',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='locations',
            field=models.ManyToManyField(blank=True, to='company.Location', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Price', verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='company',
            name='tags',
            field=models.ManyToManyField(blank=True, to='company.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ManyToManyField(to='company.TypeCompany', verbose_name='Type'),
        ),
    ]
