# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 22:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(db_index=True, default=True, verbose_name='Публикация')),
                ('name', models.CharField(max_length=140, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=140, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('site', models.CharField(blank=True, max_length=50, verbose_name='Site')),
                ('description', models.TextField(blank=True, max_length=350, verbose_name='Description')),
                ('img', models.ImageField(upload_to='img', verbose_name='Logo')),
                ('locations', models.ManyToManyField(blank=True, to='company.Location', verbose_name='City')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Price', verbose_name='Price')),
                ('tags', models.ManyToManyField(blank=True, to='company.Tag', verbose_name='Tags')),
                ('type', models.ManyToManyField(to='company.TypeCompany', verbose_name='Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
