# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-03 14:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id'], 'verbose_name': 'Company', 'verbose_name_plural': 'Компанії'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterModelOptions(
            name='typecompany',
            options={'ordering': ['name'], 'verbose_name': 'Company type', 'verbose_name_plural': 'Company types'},
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=140, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='avatar',
            field=stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToUUID(path='images'), verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.ManyToManyField(to='company.Location', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Price', verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='company',
            name='site',
            field=models.CharField(blank=True, max_length=50, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.TypeCompany', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='typecompany',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Company type'),
        ),
    ]
