# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='img',
            field=models.ImageField(upload_to='img', verbose_name='Logo'),
        ),
    ]
