# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-04 21:54
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='photo1',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='images'), verbose_name='Photo 1'),
        ),
        migrations.AddField(
            model_name='company',
            name='photo2',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='images'), verbose_name='Photo 2'),
        ),
        migrations.AddField(
            model_name='company',
            name='photo3',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='images'), verbose_name='Photo 3'),
        ),
    ]
