# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-02 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180625_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.ManyToManyField(to='company.Location', verbose_name='Город'),
        ),
    ]
