# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-06 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180304_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='locations',
            new_name='location',
        ),
    ]
