# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20171222_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company'},
        ),
        migrations.AlterModelTable(
            name='company',
            table=None,
        ),
    ]
