# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20171222_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typecompany',
            options={'verbose_name': 'Type company', 'verbose_name_plural': 'Type companies'},
        ),
    ]
