# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 23:16
from __future__ import unicode_literals

from django.db import migrations
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20180204_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, max_length=1000, no_rendered_field=True, verbose_name='Description'),
        ),
    ]
