# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20171222_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=140, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='site',
            field=models.CharField(blank=True, max_length=50, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.ManyToManyField(blank=True, to='company.TypeCompany', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Tag name'),
        ),
        migrations.AlterField(
            model_name='typecompany',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Type company'),
        ),
    ]
