# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20171223_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='img',
            field=models.ImageField(blank=True, upload_to='img', verbose_name='Logo'),
        ),
    ]
