# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20171223_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typecompany',
            options={'verbose_name': 'Company type', 'verbose_name_plural': 'Company types'},
        ),
        migrations.AlterField(
            model_name='typecompany',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Company type'),
        ),
    ]
