# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20171223_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(db_index=True, default=True, verbose_name='Публикация')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Price')),
                ('slug', models.SlugField(blank=True, max_length=140, null=True)),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Место проведения', 'verbose_name_plural': 'Места проведения'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterModelOptions(
            name='typecompany',
            options={'verbose_name': 'Тип компании', 'verbose_name_plural': 'Типы компании'},
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=140, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='company',
            name='img',
            field=models.ImageField(blank=True, upload_to='img', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='company',
            name='site',
            field=models.CharField(blank=True, max_length=50, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.ManyToManyField(blank=True, to='company.TypeCompany', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Имя тэга'),
        ),
        migrations.AlterField(
            model_name='typecompany',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Тип компании'),
        ),
        migrations.AddField(
            model_name='company',
            name='price',
            field=models.ForeignKey(blank=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='company.Price'),
            preserve_default=False,
        ),
    ]
