# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20171227_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Место проведения', 'verbose_name_plural': 'Места проведения'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Стоимость', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterModelOptions(
            name='typecompany',
            options={'ordering': ['name'], 'verbose_name': 'Тип компании', 'verbose_name_plural': 'Типы компании'},
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Стоимость'),
        ),
    ]
