# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20180106_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, max_length=350, verbose_name='Описание'),
        ),
    ]
