# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20180106_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='company',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Price', verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tags',
            field=models.ManyToManyField(blank=True, to='company.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.ManyToManyField(to='company.TypeCompany', verbose_name='Тип'),
        ),
    ]
